version: "3.7"
services:
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
